language: python
addons:
  postgresql: 9.2
env:
  global:
  - TESTMODEL_URL=http://localhost:8080/intermine-demo
  - TESTMODEL_PATH=intermine-demo  
  matrix:
  # Disable Selenium tests    
  # - TEST_SUITE=webapp
  - TEST_SUITE=bio
  - TEST_SUITE=ws CLIENT=JS
  - TEST_SUITE=ws CLIENT=PY
  - TEST_SUITE=all
  - TEST_SUITE=webtasks
  - TEST_SUITE=checkstyle
sudo: true
jdk:
- openjdk8
before_script:
- "./config/travis/init.sh"
before_install:
- export DISPLAY=:99.0
- "./config/travis/before-install.sh"
script:
- "./config/travis/run.sh"
